import { User, SolutionSheet, Project, HelpRequest } from '@shared/index';

export const FALLBACK_USERS: User[] = [
  {
    id: 'user-koffi',
    name: 'Koffi Mensah',
    email: 'koffi@koradevs.bj',
    city: 'Cotonou',
    stack: ['React', 'Node.js', 'TypeScript', 'Tailwind'],
    bio: 'Développeur Fullstack junior à Cotonou. Passionné par le web moderne et l’entraide.',
    doorOpen: true,
    points: 120,
    role: 'demandeur',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'user-aicha',
    name: 'Aïcha Diop',
    email: 'aicha@koradevs.sn',
    city: 'Dakar',
    stack: ['Python', 'TypeScript', 'React', 'FastAPI', 'Docker'],
    bio: 'Lead dev backend à Dakar. Toujours disponible pour prêter main-forte aux voisins.',
    doorOpen: true,
    points: 480,
    role: 'aidant',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'user-samba',
    name: 'Samba Sow',
    email: 'samba@koradevs.ci',
    city: 'Abidjan',
    stack: ['Flutter', 'Node.js', 'PostgreSQL', 'Dart'],
    bio: 'Architecte Mobile & Cloud à Abidjan. Adepte du test-driven development.',
    doorOpen: true,
    points: 310,
    role: 'mentor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
  },
];

export const FALLBACK_SOLUTIONS: SolutionSheet[] = [
  {
    id: 'sol-1',
    title: 'Résoudre les requêtes CORS bloquées entre React Vite et Express',
    problem: 'Les requêtes HTTP POST envoyées depuis React Vite (port 5173) vers Express (port 3001) échouent avec une erreur de politique CORS.',
    cause: 'Le serveur Express ne renvoyait pas l’en-tête Access-Control-Allow-Origin autorisant l’origine du client.',
    solution: 'Installer le middleware cors, l’appliquer avant les routes et spécifier origin: "http://localhost:5173" avec credentials: true.',
    codeSnippet: "import cors from 'cors';\napp.use(cors({ origin: 'http://localhost:5173', credentials: true }));",
    stackTag: 'React',
    authorId: 'user-koffi',
    authorName: 'Koffi Mensah',
    helperId: 'user-aicha',
    helperName: 'Aïcha Diop',
    publishedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    upvotes: 14,
    proofHash: 'hash-proof-cors-2026-cadev',
  },
  {
    id: 'sol-2',
    title: 'Éviter les boucles infinies async avec useEffect en React',
    problem: 'Le composant React boucle indéfiniment lors du chargement des données d’API utilisateur.',
    cause: 'L’absence du tableau de dépendances dans useEffect réexécutait la fonction asynchrone à chaque re-render.',
    solution: 'Passer un tableau de dépendances vide [] pour exécuter la requête uniquement au montage du composant.',
    codeSnippet: 'useEffect(() => {\n  async function load() { const res = await fetch("/api/user"); setUser(await res.json()); }\n  load();\n}, []);',
    stackTag: 'TypeScript',
    authorId: 'user-samba',
    authorName: 'Samba Sow',
    helperId: 'user-aicha',
    helperName: 'Aïcha Diop',
    publishedAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    upvotes: 28,
    proofHash: 'hash-proof-useeffect-2026',
  },
  {
    id: 'sol-3',
    title: 'Gestion sécurisée des JWT en HttpOnly Cookies avec Next.js & Express',
    problem: 'Vulnérabilité XSS lors du stockage du jeton d’authentification dans localStorage.',
    cause: 'Le token JWT était accessible par n’importe quel script tiers injecté dans le DOM.',
    solution: 'Stocker le token dans un cookie HttpOnly sécurisé avec SameSite=Lax et transmettre les credentials automatiquement.',
    codeSnippet: "res.cookie('token', jwtToken, { httpOnly: true, secure: true, sameSite: 'lax' });",
    stackTag: 'Node.js',
    authorId: 'user-koffi',
    authorName: 'Koffi Mensah',
    helperId: 'user-samba',
    helperName: 'Samba Sow',
    publishedAt: new Date(Date.now() - 3600000 * 72).toISOString(),
    upvotes: 35,
    proofHash: 'hash-proof-security-jwt-2026',
  },
];

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'KoraCode CLI & SDK',
    description: 'Suite d’outils open-source CLI et SDK pour accélérer le développement d’applications Web & PWA en Afrique de l’Ouest.',
    demoUrl: 'https://koracode.dev',
    repoUrl: 'https://github.com/koradevs/koracode-sdk',
    rolesNeeded: [
      'Développeur Rust / Node.js',
      'Designer UI/UX',
      'Dev Backend TypeScript',
    ],
    authorId: 'user-koffi',
    authorName: 'Koffi Mensah',
    city: 'Cotonou',
    membersCount: 3,
    tasks: [
      { id: 'task-1', title: 'Concevoir la commande CLI init', status: 'done', assigneeName: 'Koffi Mensah' },
      { id: 'task-2', title: 'Connecter l’API de génération de tokens', status: 'in_progress', assigneeName: 'Aïcha Diop' },
      { id: 'task-3', title: 'Ajouter l’export des certificats cryptographiques', status: 'todo' },
    ],
    createdAt: new Date(Date.now() - 3600000 * 96).toISOString(),
  },
  {
    id: 'proj-2',
    name: 'EduDev WestAfrica',
    description: 'Plateforme de ressources éducatives hors-ligne et fiches interactives pour étudiants et apprenants en informatique.',
    demoUrl: 'https://edudev.africa',
    repoUrl: 'https://github.com/koradevs/edudev',
    rolesNeeded: [
      'Rédacteur de fiches techniques',
      'Développeur React',
      'Traducteur Wolof / Fon',
    ],
    authorId: 'user-samba',
    authorName: 'Samba Sow',
    city: 'Abidjan',
    membersCount: 5,
    tasks: [
      { id: 'task-10', title: 'Rédiger le cours TypeScript moderne', status: 'done', assigneeName: 'Samba Sow' },
      { id: 'task-11', title: 'Implémenter le lecteur PWA hors-ligne', status: 'in_progress' },
    ],
    createdAt: new Date(Date.now() - 3600000 * 120).toISOString(),
  },
];

export const FALLBACK_REQUESTS: HelpRequest[] = [
  {
    id: 'req-1',
    title: 'Erreur CORS sur API Express avec React Vite',
    description: 'Mon application React client bloque lors des appels POST vers mon serveur local Express. Le navigateur affiche "Blocked by CORS policy".',
    code: "fetch('http://localhost:3001/api/data', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ token: '***[SECRET MASQUÉ]***' })\n});",
    cleanCode: "fetch('http://localhost:3001/api/data', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ token: '***[SECRET MASQUÉ]***' })\n});",
    secretsMaskedCount: 1,
    stackTag: 'React',
    status: 'pending',
    requesterId: 'user-koffi',
    requesterName: 'Koffi Mensah',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'req-2',
    title: 'Crash Async/Await dans useEffect sans cleanup',
    description: 'L’effect React s’exécute en boucle infinie quand je tente de charger les données utilisateur.',
    code: "useEffect(() => {\n  async function load() {\n    const res = await fetch('/api/user');\n    setUser(await res.json());\n  }\n  load();\n});",
    cleanCode: "useEffect(() => {\n  async function load() {\n    const res = await fetch('/api/user');\n    setUser(await res.json());\n  }\n  load();\n}, []);",
    secretsMaskedCount: 0,
    stackTag: 'TypeScript',
    status: 'pending',
    requesterId: 'user-koffi',
    requesterName: 'Koffi Mensah',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
];
